# Generated by Django 4.1 on 2022-08-15 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_ordermodel_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='collection_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
