# Generated by Django 4.1 on 2022-08-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_ordermodel_collection_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='collection_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
