# Generated by Django 4.1 on 2022-08-15 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_ordermodel_collection_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
