# Generated by Django 4.1 on 2022-08-11 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='booking_date',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='wash_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
