# Generated by Django 4.1 on 2022-08-12 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_ordermodel_booking_date_ordermodel_wash_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
